# Generated by Django 3.2.7 on 2021-09-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'avaliacoes'},
        ),
    ]
